# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc0438d1c4d95bd2b48199f4d96dc7242973fe0a336a3bdbc766e79f7bff1c13224541477d22ab1060c65891fbc8303432c079325ef34ef892e30c404b833495

test:
  secret_key_base: 43650f4abbd14c3551bc69136c9312446f3660f91aac9cfcbe7a872c8fe217b6293633a4cffa5ad079c2a29655facd32b98c5b9e6528a4a58da640ddf3908a6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
